on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
  LW_API_KEY: ${{ secrets.LW_API_KEY }}
  LW_API_SECRET: ${{ secrets.LW_API_SECRET }}

name: Lacework Code Analysis (PR)
jobs:
  run-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [new, old]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
    #   - uses: gradle/actions/setup-gradle@v3
    #     id: setup-gradle
    #     with:
    #       gradle-version: 7.3.1
      - name: Checkout old
        if: ${{ matrix.target == 'old' }}
        run: |
            git checkout HEAD^1
    #   - run: |
    #         gradle bootJar --no-daemon
    #         ./gradlew publishToMavenLocal
    #         cp build/publications/mavenJava/pom-default.xml pom.xml
      - run: mvn package
      - name: Analyze
        uses: lacework/code-security-action@v1
        with:
          classes: build/libs/log4shell-vulnerable-app-0.0.1-SNAPSHOT.jar
          target: ${{ matrix.target }}
          debug: true
          tools: sca
          autofix: true
  display-results:
    runs-on: ubuntu-latest
    name: Display results
    needs:
      - run-analysis
    steps:
      - name: Results
        id: code-analysis
        uses: lacework/code-security-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true